In [1]:

import importlib
import numpy as np
import pandas as pd
import torch

from sklearn.model_selection import train_test_split
import functions
from model.cnn_model import Simple3DCNN, Simple3DCNNLarge, ProfileMLP


importlib.reload(functions)
from notebooks.OOF.functions import train_profile_mlp, predict_profile_mlp, train_cnn_model, predict_cnn_model


import joblib

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    log_loss,
    roc_auc_score,
)
from sklearn.model_selection import (
    GridSearchCV,
    StratifiedKFold,
)
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from pathlib import Path

In [2]:
project_dir = Path.cwd().parents[1]

# Jeżeli notebook znajduje się np. w katalogu src:
if not (project_dir / "data").exists():
    project_dir = project_dir.parent

niftis_dir = project_dir / "data" / "niftis"
labels_path = niftis_dir / "train_labels_JNDlMjr.csv"

outputs_dir = project_dir / "src" / "outputs"
outputs_dir.mkdir(parents=True, exist_ok=True)

labels_df = pd.read_csv(labels_path)

target_column = "is_pathologic"

labels = labels_df.set_index("uid")[target_column]

nifti_paths = sorted(niftis_dir.glob("*.nii.gz"))

print("Katalog projektu:", project_dir)
print("Liczba obrazów:", len(nifti_paths))
print("Liczba etykiet:", len(labels))

Katalog projektu: C:\Users\abram\PycharmProjects\DrivenData_DAT_Parkinsons
Liczba obrazów: 1363
Liczba etykiet: 1362

In [3]:
data_processed_volume = np.load(
    project_dir / "data" / "processed_volumes_with_rotation_by_similarity.npz",
    allow_pickle=False,
)

X_volumes = data_processed_volume["X"].astype(np.float32)
y_volumes = data_processed_volume["y"].astype(np.int64)
uids_processed_volumes = data_processed_volume["uid"]

data_profiles = np.load(
    project_dir / "data" / "processed_profiles.npz",
    allow_pickle=False,
)

print(data_profiles.files)

uids_profiles = data_profiles["uid"]
y_profiles = data_profiles["is_pathologic"].astype(np.int64)

x_profile = data_profiles["x_profile"]
y_profile = data_profiles["y_profile"]
z_profile = data_profiles["z_profile"]
rotation_x_profile = data_profiles["rotation_x_profile"]
tilt_x_profiles = data_profiles["tilt_x_profiles"]
pitch_y_profiles = data_profiles["pitch_y_profiles"]

print("Volumes:", X_volumes.shape, y_volumes.shape, uids_processed_volumes.shape)
print("Profiles:", y_profiles.shape, uids_profiles.shape)

print("UID order equal:", np.array_equal(uids_processed_volumes, uids_profiles))
print("Labels equal:", np.array_equal(y_volumes, y_profiles))

assert np.array_equal(uids_processed_volumes, uids_profiles)
assert np.array_equal(y_volumes, y_profiles)

uid_to_idx = {
    uid: idx
    for idx, uid in enumerate(uids_processed_volumes)
}

['uid', 'is_pathologic', 'x_profile', 'y_profile', 'z_profile', 'rotation_x_profile', 'tilt_x_profiles', 'pitch_y_profiles']
Volumes: (1362, 1, 50, 60, 30) (1362,) (1362,)
Profiles: (1362,) (1362,)
UID order equal: True
Labels equal: True

In [4]:
split_df = pd.DataFrame({
    "uid": uids_processed_volumes,
    "is_pathologic": y_volumes,
})

train_main_df, temp_df = train_test_split(
    split_df,
    test_size=0.3,
    stratify=split_df["is_pathologic"],
    random_state=42,
)

valid_meta_df, test_final_df = train_test_split(
    temp_df,
    test_size=1/3,
    stratify=temp_df["is_pathologic"],
    random_state=42,
)

train_main_df = train_main_df.reset_index(drop=True)
valid_meta_df = valid_meta_df.reset_index(drop=True)
test_final_df = test_final_df.reset_index(drop=True)

train_main_df["split"] = "train_main"
valid_meta_df["split"] = "valid_meta"
test_final_df["split"] = "test_final"

train_main_df["fold"] = -1
valid_meta_df["fold"] = -1
test_final_df["fold"] = -1

skf = StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=42,
)

for fold, (_, val_idx) in enumerate(
    skf.split(
        train_main_df["uid"],
        train_main_df["is_pathologic"],
    )
):
    train_main_df.loc[val_idx, "fold"] = fold

oof_split_df = pd.concat(
    [
        train_main_df,
        valid_meta_df,
        test_final_df,
    ],
    ignore_index=True,
)

oof_split_df.to_csv(
    "oof_split.csv",
    index=False,
)

print(oof_split_df["split"].value_counts())
print(pd.crosstab(oof_split_df["split"], oof_split_df["is_pathologic"]))
print(pd.crosstab(train_main_df["fold"], train_main_df["is_pathologic"]))

assert oof_split_df["uid"].is_unique
assert set(train_main_df["fold"]) == set(range(5))

split
train_main    953
valid_meta    272
test_final    137
Name: count, dtype: int64
is_pathologic    0    1
split
test_final      62   75
train_main     430  523
valid_meta     123  149
is_pathologic   0    1
fold
0              86  105
1              86  105
2              86  105
3              86  104
4              86  104

In [5]:
print(oof_split_df.groupby("split")["is_pathologic"].mean())
print(train_main_df.groupby("fold")["is_pathologic"].mean())

split
test_final    0.547445
train_main    0.548793
valid_meta    0.547794
Name: is_pathologic, dtype: float64
fold
0    0.549738
1    0.549738
2    0.549738
3    0.547368
4    0.547368
Name: is_pathologic, dtype: float64

In [6]:
X_profiles = np.concatenate(
    [
        x_profile,
        y_profile,
        z_profile,
        rotation_x_profile,
    ],
    axis=1,
).astype(np.float32)
def add_result(results, model_name, fold, y_true, y_proba):
    results.append({
        "model": model_name,
        "fold": fold,
        "log_loss": log_loss(y_true, y_proba),
        "auroc": roc_auc_score(y_true, y_proba),
    })

In [7]:

results = []
for fold in range(5):
    print(f"\nFold {fold}")

    train_uids = oof_split_df.loc[
        (oof_split_df["split"] == "train_main")
        & (oof_split_df["fold"] != fold),
        "uid"
    ].to_numpy()

    valid_uids = oof_split_df.loc[
        (oof_split_df["split"] == "train_main")
        & (oof_split_df["fold"] == fold),
        "uid"
    ].to_numpy()

    train_idx = np.array([uid_to_idx[uid] for uid in train_uids])
    valid_idx = np.array([uid_to_idx[uid] for uid in valid_uids])

    y_train = y_volumes[train_idx]
    y_valid = y_volumes[valid_idx]

    print("train:", len(train_idx), "valid:", len(valid_idx))

    profile_logreg_pipeline = make_pipeline(
    StandardScaler(),
    LogisticRegression(
        max_iter=10000,
        random_state=42,
        solver="saga",
    )
    )

    param_grid = {
    "logisticregression__C": [0.01, 0.03, 0.1, 0.3, 1, 3, 10],
    "logisticregression__l1_ratio": [0.0, 0.25, 0.5, 0.75, 1.0],
}

    profile_logreg_grid = GridSearchCV(
        estimator=profile_logreg_pipeline,
        param_grid=param_grid,
        scoring="neg_log_loss",
        cv=3,
        n_jobs=-1,
    )

    profile_logreg_grid.fit(
        X_profiles[train_idx],
        y_train,
    )

    best_profile_logreg = profile_logreg_grid.best_estimator_

    joblib.dump(
        best_profile_logreg,
        f"models/profile_logreg_fold_{fold}.joblib",
    )

    p_profile_logreg = best_profile_logreg.predict_proba(
        X_profiles[valid_idx]
    )[:, 1]

    add_result(
        results=results,
        model_name="profile_logreg",
        fold=fold,
        y_true=y_valid,
        y_proba=p_profile_logreg,
    )

results

Fold 0
train: 762 valid: 191

Fold 1
train: 762 valid: 191

Fold 2
train: 762 valid: 191

Fold 3
train: 763 valid: 190

Fold 4
train: 763 valid: 190

[{'model': 'profile_logreg',
  'fold': 0,
  'log_loss': 0.41439083218574524,
  'auroc': 0.8942414174972314},
 {'model': 'profile_logreg',
  'fold': 1,
  'log_loss': 0.41586676239967346,
  'auroc': 0.8880398671096346},
 {'model': 'profile_logreg',
  'fold': 2,
  'log_loss': 0.4103754162788391,
  'auroc': 0.8955703211517165},
 {'model': 'profile_logreg',
  'fold': 3,
  'log_loss': 0.5313894152641296,
  'auroc': 0.8339669051878354},
 {'model': 'profile_logreg',
  'fold': 4,
  'log_loss': 0.4981141686439514,
  'auroc': 0.8353085867620752}]

In [8]:
results_df = pd.DataFrame(results)

summary_df = results_df.groupby("model").agg(
    log_loss_mean=("log_loss", "mean"),
    log_loss_std=("log_loss", "std"),
    auroc_mean=("auroc", "mean"),
    auroc_std=("auroc", "std"),
)

display(results_df)
display(summary_df)

results_df.to_csv(
    "results/profile_logreg_oof_results.csv",
    index=False,
)

            model  fold  log_loss     auroc
0  profile_logreg     0  0.414391  0.894241
1  profile_logreg     1  0.415867  0.888040
2  profile_logreg     2  0.410375  0.895570
3  profile_logreg     3  0.531389  0.833967
4  profile_logreg     4  0.498114  0.835309

                log_loss_mean  log_loss_std  auroc_mean  auroc_std
model
profile_logreg       0.454027      0.056704    0.869425   0.031887

In [7]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
device

device(type='cuda')

In [8]:
def add_result_mlp(
    mlp_results,
    model_name,
    fold,
    y_true,
    y_proba,
    params=None,
    model_path=None,
):
    row = {
        "model": model_name,
        "fold": fold,
        "log_loss": log_loss(y_true, y_proba),
        "auroc": roc_auc_score(y_true, y_proba),
    }

    if params is not None:
        row["params"] = str(params)

    if model_path is not None:
        row["model_path"] = str(model_path)

    mlp_results.append(row)

In [9]:
mlp_results = []


for fold in range(5):
    print(f"\nFold {fold}")

    train_uids = oof_split_df.loc[
        (oof_split_df["split"] == "train_main")
        & (oof_split_df["fold"] != fold),
        "uid"
    ].to_numpy()

    valid_uids = oof_split_df.loc[
        (oof_split_df["split"] == "train_main")
        & (oof_split_df["fold"] == fold),
        "uid"
    ].to_numpy()

    train_idx = np.array([uid_to_idx[uid] for uid in train_uids])
    valid_idx = np.array([uid_to_idx[uid] for uid in valid_uids])

    y_train = y_volumes[train_idx]
    y_valid = y_volumes[valid_idx]

    print("train:", len(train_idx), "valid:", len(valid_idx))

    model_profile_mlp, best_valid_loss = train_profile_mlp(
            X_train=X_profiles[train_idx],
            y_train=y_train,
            X_valid=X_profiles[valid_idx],
            y_valid=y_valid,
            input_size=X_profiles.shape[1],
            epochs=300,
            batch_size=64,
            learning_rate=1e-4,
            weight_decay=1e-4,
            patience=30,
        )

    model_path = f"models/profile_mlp_fold_{fold}.pth"

    torch.save(
            model_profile_mlp.state_dict(),
            model_path,
    )

    p_profile_mlp = predict_profile_mlp(
            model_profile_mlp,
            X_profiles[valid_idx],
    )

    add_result_mlp(
            mlp_results=mlp_results,
            model_name="profile_mlp",
            fold=fold,
            y_true=y_valid,
            y_proba=p_profile_mlp,
            params={
                "best_valid_loss": best_valid_loss,
                "model_path": str(model_path),
            },
        )

    print(mlp_results[-1])

Fold 0
train: 762 valid: 191
{'model': 'profile_mlp', 'fold': 0, 'log_loss': 0.43725958466529846, 'auroc': 0.8822812846068661, 'params': "{'best_valid_loss': 0.43725961446762085, 'model_path': 'models/profile_mlp_fold_0.pth'}"}

Fold 1
train: 762 valid: 191
{'model': 'profile_mlp', 'fold': 1, 'log_loss': 0.3943496644496918, 'auroc': 0.8987818383167221, 'params': "{'best_valid_loss': 0.3943496644496918, 'model_path': 'models/profile_mlp_fold_1.pth'}"}

Fold 2
train: 762 valid: 191
{'model': 'profile_mlp', 'fold': 2, 'log_loss': 0.4082057476043701, 'auroc': 0.8900332225913622, 'params': "{'best_valid_loss': 0.4082058072090149, 'model_path': 'models/profile_mlp_fold_2.pth'}"}

Fold 3
train: 763 valid: 190
{'model': 'profile_mlp', 'fold': 3, 'log_loss': 0.4706745445728302, 'auroc': 0.8528622540250448, 'params': "{'best_valid_loss': 0.470674604177475, 'model_path': 'models/profile_mlp_fold_3.pth'}"}

Fold 4
train: 763 valid: 190
{'model': 'profile_mlp', 'fold': 4, 'log_loss': 0.4893549978733063, 'auroc': 0.842128801431127, 'params': "{'best_valid_loss': 0.4893549978733063, 'model_path': 'models/profile_mlp_fold_4.pth'}"}

In [10]:
results_df = pd.DataFrame(mlp_results)

summary_df = results_df.groupby("model").agg(
    log_loss_mean=("log_loss", "mean"),
    log_loss_std=("log_loss", "std"),
    auroc_mean=("auroc", "mean"),
    auroc_std=("auroc", "std"),
)

display(results_df)
display(summary_df)

results_df.to_csv(
    "results/profile_mlp_oof_results.csv",
    index=False,
)

,model,fold,log_loss,auroc,params
0,profile_mlp,0,0.437260,0.882281,"{'best_valid_loss': 0.43725961446762085, 'mode..."
1,profile_mlp,1,0.394350,0.898782,"{'best_valid_loss': 0.3943496644496918, 'model..."
2,profile_mlp,2,0.408206,0.890033,"{'best_valid_loss': 0.4082058072090149, 'model..."
3,profile_mlp,3,0.470675,0.852862,"{'best_valid_loss': 0.470674604177475, 'model_..."
4,profile_mlp,4,0.489355,0.842129,"{'best_valid_loss': 0.4893549978733063, 'model..."

             log_loss_mean  log_loss_std  auroc_mean  auroc_std
model
profile_mlp       0.439969      0.040247    0.873217   0.024491

In [14]:
results_small_cnn = []

for fold in range(5):
    print(f"\nFold {fold}")

    train_uids = oof_split_df.loc[
        (oof_split_df["split"] == "train_main")
        & (oof_split_df["fold"] != fold),
        "uid"
    ].to_numpy()

    valid_uids = oof_split_df.loc[
        (oof_split_df["split"] == "train_main")
        & (oof_split_df["fold"] == fold),
        "uid"
    ].to_numpy()

    train_idx = np.array([uid_to_idx[uid] for uid in train_uids])
    valid_idx = np.array([uid_to_idx[uid] for uid in valid_uids])

    y_train = y_volumes[train_idx]
    y_valid = y_volumes[valid_idx]

    print("train:", len(train_idx), "valid:", len(valid_idx))

    # SMALL CNN
    small_model = Simple3DCNN()
    small_path = f"models/small_cnn_fold_{fold}.pth"

    small_model, small_valid_proba, small_valid_loss = train_cnn_model(
        model=small_model,
        X_train=X_volumes[train_idx],
        y_train=y_volumes[train_idx],
        X_valid=X_volumes[valid_idx],
        y_valid=y_volumes[valid_idx],
        epochs=1500,
        batch_size=8,
        learning_rate=1e-4,
        weight_decay=1e-4,
        patience=150,
    )

    torch.save(small_model.state_dict(), small_path)

    add_result_mlp(
        mlp_results=results_small_cnn,
        model_name="small_cnn",
        fold=fold,
        y_true=y_valid,
        y_proba=small_valid_proba,
        params={
            "epochs": 1500,
            "batch_size": 8,
            "lr": 1e-4,
            "weight_decay": 1e-4,
            "patience": 150,
        },
        model_path=small_path,
    )

Fold 0
train: 762 valid: 191
Epoch 001/1500 | train_loss: 0.6903 | valid_loss: 0.6875 | best: 0.6875 | patience: 0/150
Epoch 002/1500 | train_loss: 0.6858 | valid_loss: 0.6852 | best: 0.6852 | patience: 0/150
Epoch 003/1500 | train_loss: 0.6847 | valid_loss: 0.6848 | best: 0.6848 | patience: 0/150
Epoch 004/1500 | train_loss: 0.6854 | valid_loss: 0.6847 | best: 0.6847 | patience: 0/150
Epoch 005/1500 | train_loss: 0.6881 | valid_loss: 0.6844 | best: 0.6844 | patience: 0/150
Epoch 006/1500 | train_loss: 0.6858 | valid_loss: 0.6840 | best: 0.6840 | patience: 0/150
Epoch 007/1500 | train_loss: 0.6840 | valid_loss: 0.6835 | best: 0.6835 | patience: 0/150
Epoch 008/1500 | train_loss: 0.6812 | valid_loss: 0.6825 | best: 0.6825 | patience: 0/150
Epoch 009/1500 | train_loss: 0.6834 | valid_loss: 0.6818 | best: 0.6818 | patience: 0/150
Epoch 010/1500 | train_loss: 0.6807 | valid_loss: 0.6810 | best: 0.6810 | patience: 0/150
Epoch 011/1500 | train_loss: 0.6842 | valid_loss: 0.6793 | best: 0.6793 | patience: 0/150
Epoch 012/1500 | train_loss: 0.6797 | valid_loss: 0.6785 | best: 0.6785 | patience: 0/150
Epoch 013/1500 | train_loss: 0.6790 | valid_loss: 0.6770 | best: 0.6770 | patience: 0/150
Epoch 014/1500 | train_loss: 0.6730 | valid_loss: 0.6713 | best: 0.6713 | patience: 0/150
Epoch 015/1500 | train_loss: 0.6712 | valid_loss: 0.6666 | best: 0.6666 | patience: 0/150
Epoch 016/1500 | train_loss: 0.6678 | valid_loss: 0.6626 | best: 0.6626 | patience: 0/150
Epoch 017/1500 | train_loss: 0.6610 | valid_loss: 0.6605 | best: 0.6605 | patience: 0/150
Epoch 018/1500 | train_loss: 0.6554 | valid_loss: 0.6535 | best: 0.6535 | patience: 0/150
Epoch 020/1500 | train_loss: 0.6464 | valid_loss: 0.6419 | best: 0.6419 | patience: 0/150
Epoch 021/1500 | train_loss: 0.6373 | valid_loss: 0.6390 | best: 0.6390 | patience: 0/150
Epoch 022/1500 | train_loss: 0.6416 | valid_loss: 0.6326 | best: 0.6326 | patience: 0/150
Epoch 023/1500 | train_loss: 0.6382 | valid_loss: 0.6281 | best: 0.6281 | patience: 0/150
Epoch 024/1500 | train_loss: 0.6330 | valid_loss: 0.6241 | best: 0.6241 | patience: 0/150
Epoch 025/1500 | train_loss: 0.6345 | valid_loss: 0.6221 | best: 0.6221 | patience: 0/150
Epoch 026/1500 | train_loss: 0.6268 | valid_loss: 0.6187 | best: 0.6187 | patience: 0/150
Epoch 027/1500 | train_loss: 0.6157 | valid_loss: 0.6139 | best: 0.6139 | patience: 0/150
Epoch 028/1500 | train_loss: 0.6272 | valid_loss: 0.6120 | best: 0.6120 | patience: 0/150
Epoch 030/1500 | train_loss: 0.6188 | valid_loss: 0.6053 | best: 0.6053 | patience: 0/150
Epoch 032/1500 | train_loss: 0.6135 | valid_loss: 0.6029 | best: 0.6029 | patience: 0/150
Epoch 033/1500 | train_loss: 0.6108 | valid_loss: 0.6016 | best: 0.6016 | patience: 0/150
Epoch 034/1500 | train_loss: 0.6058 | valid_loss: 0.5944 | best: 0.5944 | patience: 0/150
Epoch 036/1500 | train_loss: 0.5959 | valid_loss: 0.5916 | best: 0.5916 | patience: 0/150
Epoch 037/1500 | train_loss: 0.6020 | valid_loss: 0.5892 | best: 0.5892 | patience: 0/150
Epoch 040/1500 | train_loss: 0.5998 | valid_loss: 0.5959 | best: 0.5892 | patience: 3/150
Epoch 042/1500 | train_loss: 0.5965 | valid_loss: 0.5859 | best: 0.5859 | patience: 0/150
Epoch 043/1500 | train_loss: 0.5965 | valid_loss: 0.5808 | best: 0.5808 | patience: 0/150
Epoch 046/1500 | train_loss: 0.5872 | valid_loss: 0.5786 | best: 0.5786 | patience: 0/150
Epoch 047/1500 | train_loss: 0.5922 | valid_loss: 0.5773 | best: 0.5773 | patience: 0/150
Epoch 049/1500 | train_loss: 0.5816 | valid_loss: 0.5734 | best: 0.5734 | patience: 0/150
Epoch 050/1500 | train_loss: 0.5943 | valid_loss: 0.5786 | best: 0.5734 | patience: 1/150
Epoch 051/1500 | train_loss: 0.5793 | valid_loss: 0.5717 | best: 0.5717 | patience: 0/150
Epoch 054/1500 | train_loss: 0.5784 | valid_loss: 0.5706 | best: 0.5706 | patience: 0/150
Epoch 055/1500 | train_loss: 0.5743 | valid_loss: 0.5674 | best: 0.5674 | patience: 0/150
Epoch 058/1500 | train_loss: 0.5774 | valid_loss: 0.5671 | best: 0.5671 | patience: 0/150
Epoch 059/1500 | train_loss: 0.5787 | valid_loss: 0.5647 | best: 0.5647 | patience: 0/150
Epoch 060/1500 | train_loss: 0.5841 | valid_loss: 0.5629 | best: 0.5629 | patience: 0/150
Epoch 063/1500 | train_loss: 0.5813 | valid_loss: 0.5618 | best: 0.5618 | patience: 0/150
Epoch 066/1500 | train_loss: 0.5801 | valid_loss: 0.5594 | best: 0.5594 | patience: 0/150
Epoch 067/1500 | train_loss: 0.5688 | valid_loss: 0.5593 | best: 0.5593 | patience: 0/150
Epoch 068/1500 | train_loss: 0.5695 | valid_loss: 0.5562 | best: 0.5562 | patience: 0/150
Epoch 069/1500 | train_loss: 0.5632 | valid_loss: 0.5530 | best: 0.5530 | patience: 0/150
Epoch 070/1500 | train_loss: 0.5658 | valid_loss: 0.5541 | best: 0.5530 | patience: 1/150
Epoch 072/1500 | train_loss: 0.5564 | valid_loss: 0.5490 | best: 0.5490 | patience: 0/150
Epoch 075/1500 | train_loss: 0.5542 | valid_loss: 0.5450 | best: 0.5450 | patience: 0/150
Epoch 077/1500 | train_loss: 0.5604 | valid_loss: 0.5412 | best: 0.5412 | patience: 0/150
Epoch 079/1500 | train_loss: 0.5596 | valid_loss: 0.5383 | best: 0.5383 | patience: 0/150
Epoch 080/1500 | train_loss: 0.5610 | valid_loss: 0.5375 | best: 0.5375 | patience: 0/150
Epoch 081/1500 | train_loss: 0.5567 | valid_loss: 0.5370 | best: 0.5370 | patience: 0/150
Epoch 083/1500 | train_loss: 0.5590 | valid_loss: 0.5344 | best: 0.5344 | patience: 0/150
Epoch 084/1500 | train_loss: 0.5600 | valid_loss: 0.5323 | best: 0.5323 | patience: 0/150
Epoch 085/1500 | train_loss: 0.5527 | valid_loss: 0.5308 | best: 0.5308 | patience: 0/150
Epoch 088/1500 | train_loss: 0.5570 | valid_loss: 0.5277 | best: 0.5277 | patience: 0/150
Epoch 089/1500 | train_loss: 0.5427 | valid_loss: 0.5275 | best: 0.5275 | patience: 0/150
Epoch 090/1500 | train_loss: 0.5462 | valid_loss: 0.5241 | best: 0.5241 | patience: 0/150
Epoch 091/1500 | train_loss: 0.5324 | valid_loss: 0.5211 | best: 0.5211 | patience: 0/150
Epoch 092/1500 | train_loss: 0.5455 | valid_loss: 0.5205 | best: 0.5205 | patience: 0/150
Epoch 094/1500 | train_loss: 0.5396 | valid_loss: 0.5150 | best: 0.5150 | patience: 0/150
Epoch 096/1500 | train_loss: 0.5263 | valid_loss: 0.5113 | best: 0.5113 | patience: 0/150
Epoch 097/1500 | train_loss: 0.5275 | valid_loss: 0.5096 | best: 0.5096 | patience: 0/150
Epoch 099/1500 | train_loss: 0.5134 | valid_loss: 0.5041 | best: 0.5041 | patience: 0/150
Epoch 100/1500 | train_loss: 0.5306 | valid_loss: 0.5042 | best: 0.5041 | patience: 1/150
Epoch 101/1500 | train_loss: 0.5280 | valid_loss: 0.5029 | best: 0.5029 | patience: 0/150
Epoch 102/1500 | train_loss: 0.5178 | valid_loss: 0.4996 | best: 0.4996 | patience: 0/150
Epoch 103/1500 | train_loss: 0.5311 | valid_loss: 0.4993 | best: 0.4993 | patience: 0/150
Epoch 105/1500 | train_loss: 0.5116 | valid_loss: 0.4966 | best: 0.4966 | patience: 0/150
Epoch 106/1500 | train_loss: 0.5194 | valid_loss: 0.4961 | best: 0.4961 | patience: 0/150
Epoch 107/1500 | train_loss: 0.5141 | valid_loss: 0.4914 | best: 0.4914 | patience: 0/150
Epoch 109/1500 | train_loss: 0.5268 | valid_loss: 0.4898 | best: 0.4898 | patience: 0/150
Epoch 110/1500 | train_loss: 0.5104 | valid_loss: 0.4900 | best: 0.4898 | patience: 1/150
Epoch 112/1500 | train_loss: 0.5251 | valid_loss: 0.4830 | best: 0.4830 | patience: 0/150
Epoch 115/1500 | train_loss: 0.5138 | valid_loss: 0.4806 | best: 0.4806 | patience: 0/150
Epoch 117/1500 | train_loss: 0.5108 | valid_loss: 0.4798 | best: 0.4798 | patience: 0/150
Epoch 119/1500 | train_loss: 0.4983 | valid_loss: 0.4757 | best: 0.4757 | patience: 0/150
Epoch 120/1500 | train_loss: 0.5025 | valid_loss: 0.4730 | best: 0.4730 | patience: 0/150
Epoch 121/1500 | train_loss: 0.5017 | valid_loss: 0.4718 | best: 0.4718 | patience: 0/150
Epoch 123/1500 | train_loss: 0.5030 | valid_loss: 0.4680 | best: 0.4680 | patience: 0/150
Epoch 125/1500 | train_loss: 0.4917 | valid_loss: 0.4672 | best: 0.4672 | patience: 0/150
Epoch 126/1500 | train_loss: 0.5036 | valid_loss: 0.4671 | best: 0.4671 | patience: 0/150
Epoch 127/1500 | train_loss: 0.4938 | valid_loss: 0.4617 | best: 0.4617 | patience: 0/150
Epoch 128/1500 | train_loss: 0.4708 | valid_loss: 0.4598 | best: 0.4598 | patience: 0/150
Epoch 130/1500 | train_loss: 0.4998 | valid_loss: 0.4650 | best: 0.4598 | patience: 2/150
Epoch 131/1500 | train_loss: 0.4910 | valid_loss: 0.4579 | best: 0.4579 | patience: 0/150
Epoch 138/1500 | train_loss: 0.4868 | valid_loss: 0.4514 | best: 0.4514 | patience: 0/150
Epoch 139/1500 | train_loss: 0.4784 | valid_loss: 0.4506 | best: 0.4506 | patience: 0/150
Epoch 140/1500 | train_loss: 0.4793 | valid_loss: 0.4552 | best: 0.4506 | patience: 1/150
Epoch 142/1500 | train_loss: 0.4903 | valid_loss: 0.4482 | best: 0.4482 | patience: 0/150
Epoch 143/1500 | train_loss: 0.4814 | valid_loss: 0.4450 | best: 0.4450 | patience: 0/150
Epoch 147/1500 | train_loss: 0.4704 | valid_loss: 0.4412 | best: 0.4412 | patience: 0/150
Epoch 149/1500 | train_loss: 0.4749 | valid_loss: 0.4408 | best: 0.4408 | patience: 0/150
Epoch 150/1500 | train_loss: 0.4923 | valid_loss: 0.4386 | best: 0.4386 | patience: 0/150
Epoch 154/1500 | train_loss: 0.4789 | valid_loss: 0.4356 | best: 0.4356 | patience: 0/150
Epoch 157/1500 | train_loss: 0.4784 | valid_loss: 0.4347 | best: 0.4347 | patience: 0/150
Epoch 158/1500 | train_loss: 0.4824 | valid_loss: 0.4339 | best: 0.4339 | patience: 0/150
Epoch 160/1500 | train_loss: 0.4786 | valid_loss: 0.4426 | best: 0.4339 | patience: 2/150
Epoch 161/1500 | train_loss: 0.4689 | valid_loss: 0.4286 | best: 0.4286 | patience: 0/150
Epoch 165/1500 | train_loss: 0.4685 | valid_loss: 0.4272 | best: 0.4272 | patience: 0/150
Epoch 170/1500 | train_loss: 0.4763 | valid_loss: 0.4242 | best: 0.4242 | patience: 0/150
Epoch 173/1500 | train_loss: 0.4754 | valid_loss: 0.4231 | best: 0.4231 | patience: 0/150
Epoch 176/1500 | train_loss: 0.4732 | valid_loss: 0.4223 | best: 0.4223 | patience: 0/150
Epoch 178/1500 | train_loss: 0.4649 | valid_loss: 0.4201 | best: 0.4201 | patience: 0/150
Epoch 180/1500 | train_loss: 0.4658 | valid_loss: 0.4192 | best: 0.4192 | patience: 0/150
Epoch 185/1500 | train_loss: 0.4598 | valid_loss: 0.4155 | best: 0.4155 | patience: 0/150
Epoch 190/1500 | train_loss: 0.4447 | valid_loss: 0.4155 | best: 0.4155 | patience: 0/150
Epoch 194/1500 | train_loss: 0.4560 | valid_loss: 0.4116 | best: 0.4116 | patience: 0/150
Epoch 198/1500 | train_loss: 0.4572 | valid_loss: 0.4100 | best: 0.4100 | patience: 0/150
Epoch 200/1500 | train_loss: 0.4631 | valid_loss: 0.4157 | best: 0.4100 | patience: 2/150
Epoch 201/1500 | train_loss: 0.4479 | valid_loss: 0.4082 | best: 0.4082 | patience: 0/150
Epoch 209/1500 | train_loss: 0.4485 | valid_loss: 0.4074 | best: 0.4074 | patience: 0/150
Epoch 210/1500 | train_loss: 0.4449 | valid_loss: 0.4067 | best: 0.4067 | patience: 0/150
Epoch 213/1500 | train_loss: 0.4458 | valid_loss: 0.4047 | best: 0.4047 | patience: 0/150
Epoch 220/1500 | train_loss: 0.4430 | valid_loss: 0.4021 | best: 0.4021 | patience: 0/150
Epoch 223/1500 | train_loss: 0.4448 | valid_loss: 0.3994 | best: 0.3994 | patience: 0/150
Epoch 230/1500 | train_loss: 0.4472 | valid_loss: 0.4025 | best: 0.3994 | patience: 7/150
Epoch 233/1500 | train_loss: 0.4495 | valid_loss: 0.3971 | best: 0.3971 | patience: 0/150
Epoch 234/1500 | train_loss: 0.4481 | valid_loss: 0.3967 | best: 0.3967 | patience: 0/150
Epoch 237/1500 | train_loss: 0.4319 | valid_loss: 0.3966 | best: 0.3966 | patience: 0/150
Epoch 239/1500 | train_loss: 0.4469 | valid_loss: 0.3928 | best: 0.3928 | patience: 0/150
Epoch 240/1500 | train_loss: 0.4566 | valid_loss: 0.4154 | best: 0.3928 | patience: 1/150
Epoch 243/1500 | train_loss: 0.4304 | valid_loss: 0.3907 | best: 0.3907 | patience: 0/150
Epoch 247/1500 | train_loss: 0.4234 | valid_loss: 0.3905 | best: 0.3905 | patience: 0/150
Epoch 249/1500 | train_loss: 0.4429 | valid_loss: 0.3904 | best: 0.3904 | patience: 0/150
Epoch 250/1500 | train_loss: 0.4404 | valid_loss: 0.3990 | best: 0.3904 | patience: 1/150
Epoch 252/1500 | train_loss: 0.4592 | valid_loss: 0.3884 | best: 0.3884 | patience: 0/150
Epoch 258/1500 | train_loss: 0.4252 | valid_loss: 0.3870 | best: 0.3870 | patience: 0/150
Epoch 260/1500 | train_loss: 0.4554 | valid_loss: 0.3920 | best: 0.3870 | patience: 2/150
Epoch 263/1500 | train_loss: 0.4402 | valid_loss: 0.3860 | best: 0.3860 | patience: 0/150
Epoch 264/1500 | train_loss: 0.4372 | valid_loss: 0.3857 | best: 0.3857 | patience: 0/150
Epoch 267/1500 | train_loss: 0.4230 | valid_loss: 0.3848 | best: 0.3848 | patience: 0/150
Epoch 270/1500 | train_loss: 0.4472 | valid_loss: 0.3863 | best: 0.3848 | patience: 3/150
Epoch 271/1500 | train_loss: 0.4381 | valid_loss: 0.3840 | best: 0.3840 | patience: 0/150
Epoch 274/1500 | train_loss: 0.4259 | valid_loss: 0.3830 | best: 0.3830 | patience: 0/150
Epoch 280/1500 | train_loss: 0.4325 | valid_loss: 0.4030 | best: 0.3830 | patience: 6/150
Epoch 281/1500 | train_loss: 0.4304 | valid_loss: 0.3812 | best: 0.3812 | patience: 0/150
Epoch 287/1500 | train_loss: 0.4298 | valid_loss: 0.3786 | best: 0.3786 | patience: 0/150
Epoch 290/1500 | train_loss: 0.4313 | valid_loss: 0.3793 | best: 0.3786 | patience: 3/150
Epoch 292/1500 | train_loss: 0.4180 | valid_loss: 0.3750 | best: 0.3750 | patience: 0/150
Epoch 297/1500 | train_loss: 0.4229 | valid_loss: 0.3732 | best: 0.3732 | patience: 0/150
Epoch 300/1500 | train_loss: 0.4344 | valid_loss: 0.4222 | best: 0.3732 | patience: 3/150
Epoch 304/1500 | train_loss: 0.4256 | valid_loss: 0.3718 | best: 0.3718 | patience: 0/150
Epoch 310/1500 | train_loss: 0.4094 | valid_loss: 0.3727 | best: 0.3718 | patience: 6/150
Epoch 311/1500 | train_loss: 0.4200 | valid_loss: 0.3686 | best: 0.3686 | patience: 0/150
Epoch 320/1500 | train_loss: 0.4209 | valid_loss: 0.3686 | best: 0.3686 | patience: 0/150
Epoch 324/1500 | train_loss: 0.4093 | valid_loss: 0.3684 | best: 0.3684 | patience: 0/150
Epoch 325/1500 | train_loss: 0.4231 | valid_loss: 0.3670 | best: 0.3670 | patience: 0/150
Epoch 326/1500 | train_loss: 0.4132 | valid_loss: 0.3662 | best: 0.3662 | patience: 0/150
Epoch 330/1500 | train_loss: 0.4118 | valid_loss: 0.3797 | best: 0.3662 | patience: 4/150
Epoch 334/1500 | train_loss: 0.4108 | valid_loss: 0.3657 | best: 0.3657 | patience: 0/150
Epoch 340/1500 | train_loss: 0.4165 | valid_loss: 0.3702 | best: 0.3657 | patience: 6/150
Epoch 345/1500 | train_loss: 0.4108 | valid_loss: 0.3631 | best: 0.3631 | patience: 0/150
Epoch 350/1500 | train_loss: 0.4083 | valid_loss: 0.3619 | best: 0.3619 | patience: 0/150
Epoch 352/1500 | train_loss: 0.4160 | valid_loss: 0.3608 | best: 0.3608 | patience: 0/150
Epoch 356/1500 | train_loss: 0.3884 | valid_loss: 0.3589 | best: 0.3589 | patience: 0/150
Epoch 360/1500 | train_loss: 0.4173 | valid_loss: 0.3587 | best: 0.3587 | patience: 0/150
Epoch 370/1500 | train_loss: 0.3997 | valid_loss: 0.3592 | best: 0.3587 | patience: 10/150
Epoch 374/1500 | train_loss: 0.4161 | valid_loss: 0.3574 | best: 0.3574 | patience: 0/150
Epoch 375/1500 | train_loss: 0.4300 | valid_loss: 0.3568 | best: 0.3568 | patience: 0/150
Epoch 376/1500 | train_loss: 0.4047 | valid_loss: 0.3566 | best: 0.3566 | patience: 0/150
Epoch 380/1500 | train_loss: 0.4041 | valid_loss: 0.3926 | best: 0.3566 | patience: 4/150
Epoch 381/1500 | train_loss: 0.4192 | valid_loss: 0.3538 | best: 0.3538 | patience: 0/150
Epoch 386/1500 | train_loss: 0.4089 | valid_loss: 0.3531 | best: 0.3531 | patience: 0/150
Epoch 390/1500 | train_loss: 0.4103 | valid_loss: 0.3543 | best: 0.3531 | patience: 4/150
Epoch 393/1500 | train_loss: 0.4000 | valid_loss: 0.3493 | best: 0.3493 | patience: 0/150
Epoch 400/1500 | train_loss: 0.4117 | valid_loss: 0.3698 | best: 0.3493 | patience: 7/150
Epoch 410/1500 | train_loss: 0.3798 | valid_loss: 0.3904 | best: 0.3493 | patience: 17/150
Epoch 411/1500 | train_loss: 0.3894 | valid_loss: 0.3471 | best: 0.3471 | patience: 0/150
Epoch 413/1500 | train_loss: 0.3820 | valid_loss: 0.3451 | best: 0.3451 | patience: 0/150
Epoch 420/1500 | train_loss: 0.4040 | valid_loss: 0.4234 | best: 0.3451 | patience: 7/150
Epoch 430/1500 | train_loss: 0.3996 | valid_loss: 0.3668 | best: 0.3451 | patience: 17/150
Epoch 435/1500 | train_loss: 0.3841 | valid_loss: 0.3445 | best: 0.3445 | patience: 0/150
Epoch 440/1500 | train_loss: 0.3947 | valid_loss: 0.3476 | best: 0.3445 | patience: 5/150
Epoch 450/1500 | train_loss: 0.4044 | valid_loss: 0.3533 | best: 0.3445 | patience: 15/150
Epoch 457/1500 | train_loss: 0.3870 | valid_loss: 0.3423 | best: 0.3423 | patience: 0/150
Epoch 459/1500 | train_loss: 0.3838 | valid_loss: 0.3418 | best: 0.3418 | patience: 0/150
Epoch 460/1500 | train_loss: 0.3809 | valid_loss: 0.3405 | best: 0.3405 | patience: 0/150
Epoch 464/1500 | train_loss: 0.3810 | valid_loss: 0.3390 | best: 0.3390 | patience: 0/150
Epoch 469/1500 | train_loss: 0.3810 | valid_loss: 0.3389 | best: 0.3389 | patience: 0/150
Epoch 470/1500 | train_loss: 0.3867 | valid_loss: 0.3396 | best: 0.3389 | patience: 1/150
Epoch 480/1500 | train_loss: 0.3845 | valid_loss: 0.3493 | best: 0.3389 | patience: 11/150
Epoch 483/1500 | train_loss: 0.3842 | valid_loss: 0.3384 | best: 0.3384 | patience: 0/150
Epoch 490/1500 | train_loss: 0.4046 | valid_loss: 0.3884 | best: 0.3384 | patience: 7/150
Epoch 495/1500 | train_loss: 0.3958 | valid_loss: 0.3364 | best: 0.3364 | patience: 0/150
Epoch 499/1500 | train_loss: 0.4019 | valid_loss: 0.3354 | best: 0.3354 | patience: 0/150
Epoch 500/1500 | train_loss: 0.3772 | valid_loss: 0.3357 | best: 0.3354 | patience: 1/150
Epoch 506/1500 | train_loss: 0.3709 | valid_loss: 0.3351 | best: 0.3351 | patience: 0/150
Epoch 510/1500 | train_loss: 0.3948 | valid_loss: 0.3429 | best: 0.3351 | patience: 4/150
Epoch 520/1500 | train_loss: 0.3781 | valid_loss: 0.3502 | best: 0.3351 | patience: 14/150
Epoch 527/1500 | train_loss: 0.3762 | valid_loss: 0.3319 | best: 0.3319 | patience: 0/150
Epoch 530/1500 | train_loss: 0.3897 | valid_loss: 0.3488 | best: 0.3319 | patience: 3/150
Epoch 540/1500 | train_loss: 0.3901 | valid_loss: 0.3349 | best: 0.3319 | patience: 13/150
Epoch 542/1500 | train_loss: 0.3743 | valid_loss: 0.3309 | best: 0.3309 | patience: 0/150
Epoch 550/1500 | train_loss: 0.3668 | valid_loss: 0.3335 | best: 0.3309 | patience: 8/150
Epoch 557/1500 | train_loss: 0.3742 | valid_loss: 0.3288 | best: 0.3288 | patience: 0/150
Epoch 560/1500 | train_loss: 0.3809 | valid_loss: 0.3305 | best: 0.3288 | patience: 3/150
Epoch 563/1500 | train_loss: 0.3831 | valid_loss: 0.3273 | best: 0.3273 | patience: 0/150
Epoch 570/1500 | train_loss: 0.3817 | valid_loss: 0.3370 | best: 0.3273 | patience: 7/150
Epoch 580/1500 | train_loss: 0.3685 | valid_loss: 0.3263 | best: 0.3263 | patience: 0/150
Epoch 583/1500 | train_loss: 0.3629 | valid_loss: 0.3235 | best: 0.3235 | patience: 0/150
Epoch 590/1500 | train_loss: 0.3819 | valid_loss: 0.3289 | best: 0.3235 | patience: 7/150
Epoch 600/1500 | train_loss: 0.3653 | valid_loss: 0.3532 | best: 0.3235 | patience: 17/150
Epoch 602/1500 | train_loss: 0.3677 | valid_loss: 0.3228 | best: 0.3228 | patience: 0/150
Epoch 604/1500 | train_loss: 0.3634 | valid_loss: 0.3209 | best: 0.3209 | patience: 0/150
Epoch 610/1500 | train_loss: 0.3869 | valid_loss: 0.3294 | best: 0.3209 | patience: 6/150
Epoch 620/1500 | train_loss: 0.3676 | valid_loss: 0.3266 | best: 0.3209 | patience: 16/150
Epoch 627/1500 | train_loss: 0.3658 | valid_loss: 0.3207 | best: 0.3207 | patience: 0/150
Epoch 630/1500 | train_loss: 0.3699 | valid_loss: 0.3244 | best: 0.3207 | patience: 3/150
Epoch 632/1500 | train_loss: 0.3676 | valid_loss: 0.3206 | best: 0.3206 | patience: 0/150
Epoch 634/1500 | train_loss: 0.3758 | valid_loss: 0.3189 | best: 0.3189 | patience: 0/150
Epoch 640/1500 | train_loss: 0.3543 | valid_loss: 0.3174 | best: 0.3174 | patience: 0/150
Epoch 650/1500 | train_loss: 0.3690 | valid_loss: 0.3207 | best: 0.3174 | patience: 10/150
Epoch 658/1500 | train_loss: 0.3651 | valid_loss: 0.3162 | best: 0.3162 | patience: 0/150
Epoch 660/1500 | train_loss: 0.3661 | valid_loss: 0.3291 | best: 0.3162 | patience: 2/150

In [15]:
results_df = pd.DataFrame(results_small_cnn)

summary_df = results_df.groupby("model").agg(
    log_loss_mean=("log_loss", "mean"),
    log_loss_std=("log_loss", "std"),
    auroc_mean=("auroc", "mean"),
    auroc_std=("auroc", "std"),
)

display(results_df)
display(summary_df)

results_df.to_csv(
    "results/profile_smal_cnn_oof_results.csv",
    index=False,
)

,model,fold,log_loss,auroc,params,model_path
0,small_cnn,0,0.269521,0.955925,"{'epochs': 1500, 'batch_size': 8, 'lr': 0.0001...",models/small_cnn_fold_0.pth
1,small_cnn,1,0.327389,0.932226,"{'epochs': 1500, 'batch_size': 8, 'lr': 0.0001...",models/small_cnn_fold_1.pth
2,small_cnn,2,0.238415,0.964673,"{'epochs': 1500, 'batch_size': 8, 'lr': 0.0001...",models/small_cnn_fold_2.pth
3,small_cnn,3,0.404473,0.900939,"{'epochs': 1500, 'batch_size': 8, 'lr': 0.0001...",models/small_cnn_fold_3.pth
4,small_cnn,4,0.251899,0.961315,"{'epochs': 1500, 'batch_size': 8, 'lr': 0.0001...",models/small_cnn_fold_4.pth

           log_loss_mean  log_loss_std  auroc_mean  auroc_std
model
small_cnn       0.298339      0.068349    0.943016   0.026727

In [18]:
results_large_cnn = []

for fold in range(5):
    print(f"\nFold {fold}")

    train_uids = oof_split_df.loc[
        (oof_split_df["split"] == "train_main")
        & (oof_split_df["fold"] != fold),
        "uid"
    ].to_numpy()

    valid_uids = oof_split_df.loc[
        (oof_split_df["split"] == "train_main")
        & (oof_split_df["fold"] == fold),
        "uid"
    ].to_numpy()

    train_idx = np.array([uid_to_idx[uid] for uid in train_uids])
    valid_idx = np.array([uid_to_idx[uid] for uid in valid_uids])

    y_train = y_volumes[train_idx]
    y_valid = y_volumes[valid_idx]

    print("train:", len(train_idx), "valid:", len(valid_idx))

    # Large CNN
    large_model = Simple3DCNNLarge()
    large_path = f"models/large_cnn_fold_{fold}.pth"

    large_model, large_valid_proba, large_valid_loss = train_cnn_model(
        model=large_model,
        X_train=X_volumes[train_idx],
        y_train=y_volumes[train_idx],
        X_valid=X_volumes[valid_idx],
        y_valid=y_volumes[valid_idx],
        epochs=2500,
        batch_size=8,
        learning_rate=1e-4,
        weight_decay=1e-4,
        patience=150,
    )

    torch.save(large_model.state_dict(), large_path)

    add_result_mlp(
        mlp_results=results_large_cnn,
        model_name="large_cnn",
        fold=fold,
        y_true=y_valid,
        y_proba=large_valid_proba,
        params={
            "epochs": 2500,
            "batch_size": 8,
            "lr": 1e-4,
            "weight_decay": 1e-4,
            "patience": 150,
        },
        model_path=large_path,
    )

Fold 0
train: 762 valid: 191
Epoch 001/2500 | train_loss: 0.6878 | valid_loss: 0.6879 | best: 0.6879 | patience: 0/150
Epoch 002/2500 | train_loss: 0.6879 | valid_loss: 0.6871 | best: 0.6871 | patience: 0/150
Epoch 003/2500 | train_loss: 0.6868 | valid_loss: 0.6867 | best: 0.6867 | patience: 0/150
Epoch 004/2500 | train_loss: 0.6859 | valid_loss: 0.6858 | best: 0.6858 | patience: 0/150
Epoch 005/2500 | train_loss: 0.6850 | valid_loss: 0.6849 | best: 0.6849 | patience: 0/150
Epoch 006/2500 | train_loss: 0.6859 | valid_loss: 0.6835 | best: 0.6835 | patience: 0/150
Epoch 007/2500 | train_loss: 0.6830 | valid_loss: 0.6810 | best: 0.6810 | patience: 0/150
Epoch 008/2500 | train_loss: 0.6799 | valid_loss: 0.6768 | best: 0.6768 | patience: 0/150
Epoch 009/2500 | train_loss: 0.6740 | valid_loss: 0.6729 | best: 0.6729 | patience: 0/150
Epoch 010/2500 | train_loss: 0.6720 | valid_loss: 0.6638 | best: 0.6638 | patience: 0/150
Epoch 011/2500 | train_loss: 0.6625 | valid_loss: 0.6513 | best: 0.6513 | patience: 0/150
Epoch 012/2500 | train_loss: 0.6552 | valid_loss: 0.6415 | best: 0.6415 | patience: 0/150
Epoch 013/2500 | train_loss: 0.6441 | valid_loss: 0.6274 | best: 0.6274 | patience: 0/150
Epoch 014/2500 | train_loss: 0.6317 | valid_loss: 0.6181 | best: 0.6181 | patience: 0/150
Epoch 016/2500 | train_loss: 0.6112 | valid_loss: 0.5845 | best: 0.5845 | patience: 0/150
Epoch 017/2500 | train_loss: 0.5908 | valid_loss: 0.5645 | best: 0.5645 | patience: 0/150
Epoch 018/2500 | train_loss: 0.5812 | valid_loss: 0.5541 | best: 0.5541 | patience: 0/150
Epoch 020/2500 | train_loss: 0.5779 | valid_loss: 0.5454 | best: 0.5454 | patience: 0/150
Epoch 022/2500 | train_loss: 0.5685 | valid_loss: 0.5294 | best: 0.5294 | patience: 0/150
Epoch 024/2500 | train_loss: 0.5589 | valid_loss: 0.5231 | best: 0.5231 | patience: 0/150
Epoch 025/2500 | train_loss: 0.5579 | valid_loss: 0.5172 | best: 0.5172 | patience: 0/150
Epoch 026/2500 | train_loss: 0.5304 | valid_loss: 0.5135 | best: 0.5135 | patience: 0/150
Epoch 028/2500 | train_loss: 0.5438 | valid_loss: 0.5117 | best: 0.5117 | patience: 0/150
Epoch 030/2500 | train_loss: 0.5413 | valid_loss: 0.5333 | best: 0.5117 | patience: 2/150
Epoch 031/2500 | train_loss: 0.5359 | valid_loss: 0.5002 | best: 0.5002 | patience: 0/150
Epoch 032/2500 | train_loss: 0.5280 | valid_loss: 0.4989 | best: 0.4989 | patience: 0/150
Epoch 035/2500 | train_loss: 0.5257 | valid_loss: 0.4851 | best: 0.4851 | patience: 0/150
Epoch 039/2500 | train_loss: 0.5191 | valid_loss: 0.4744 | best: 0.4744 | patience: 0/150
Epoch 040/2500 | train_loss: 0.5119 | valid_loss: 0.4754 | best: 0.4744 | patience: 1/150
Epoch 041/2500 | train_loss: 0.5087 | valid_loss: 0.4678 | best: 0.4678 | patience: 0/150
Epoch 044/2500 | train_loss: 0.4975 | valid_loss: 0.4576 | best: 0.4576 | patience: 0/150
Epoch 045/2500 | train_loss: 0.5102 | valid_loss: 0.4572 | best: 0.4572 | patience: 0/150
Epoch 048/2500 | train_loss: 0.4924 | valid_loss: 0.4449 | best: 0.4449 | patience: 0/150
Epoch 049/2500 | train_loss: 0.4980 | valid_loss: 0.4410 | best: 0.4410 | patience: 0/150
Epoch 050/2500 | train_loss: 0.4927 | valid_loss: 0.4413 | best: 0.4410 | patience: 1/150
Epoch 051/2500 | train_loss: 0.5029 | valid_loss: 0.4403 | best: 0.4403 | patience: 0/150
Epoch 052/2500 | train_loss: 0.4805 | valid_loss: 0.4358 | best: 0.4358 | patience: 0/150
Epoch 054/2500 | train_loss: 0.4789 | valid_loss: 0.4354 | best: 0.4354 | patience: 0/150
Epoch 058/2500 | train_loss: 0.4876 | valid_loss: 0.4322 | best: 0.4322 | patience: 0/150
Epoch 060/2500 | train_loss: 0.4732 | valid_loss: 0.4261 | best: 0.4261 | patience: 0/150
Epoch 061/2500 | train_loss: 0.4651 | valid_loss: 0.4202 | best: 0.4202 | patience: 0/150
Epoch 066/2500 | train_loss: 0.4641 | valid_loss: 0.4150 | best: 0.4150 | patience: 0/150
Epoch 070/2500 | train_loss: 0.4782 | valid_loss: 0.4151 | best: 0.4150 | patience: 4/150
Epoch 071/2500 | train_loss: 0.4561 | valid_loss: 0.4092 | best: 0.4092 | patience: 0/150
Epoch 072/2500 | train_loss: 0.4655 | valid_loss: 0.4085 | best: 0.4085 | patience: 0/150
Epoch 075/2500 | train_loss: 0.4662 | valid_loss: 0.4050 | best: 0.4050 | patience: 0/150
Epoch 076/2500 | train_loss: 0.4644 | valid_loss: 0.4030 | best: 0.4030 | patience: 0/150
Epoch 079/2500 | train_loss: 0.4651 | valid_loss: 0.4018 | best: 0.4018 | patience: 0/150
Epoch 080/2500 | train_loss: 0.4541 | valid_loss: 0.4229 | best: 0.4018 | patience: 1/150
Epoch 081/2500 | train_loss: 0.4655 | valid_loss: 0.4017 | best: 0.4017 | patience: 0/150
Epoch 086/2500 | train_loss: 0.4551 | valid_loss: 0.4011 | best: 0.4011 | patience: 0/150
Epoch 088/2500 | train_loss: 0.4630 | valid_loss: 0.3973 | best: 0.3973 | patience: 0/150
Epoch 090/2500 | train_loss: 0.4720 | valid_loss: 0.3991 | best: 0.3973 | patience: 2/150
Epoch 091/2500 | train_loss: 0.4562 | valid_loss: 0.3972 | best: 0.3972 | patience: 0/150
Epoch 095/2500 | train_loss: 0.4593 | valid_loss: 0.3934 | best: 0.3934 | patience: 0/150
Epoch 096/2500 | train_loss: 0.4627 | valid_loss: 0.3921 | best: 0.3921 | patience: 0/150
Epoch 098/2500 | train_loss: 0.4576 | valid_loss: 0.3892 | best: 0.3892 | patience: 0/150
Epoch 100/2500 | train_loss: 0.4424 | valid_loss: 0.3899 | best: 0.3892 | patience: 2/150
Epoch 102/2500 | train_loss: 0.4389 | valid_loss: 0.3833 | best: 0.3833 | patience: 0/150
Epoch 110/2500 | train_loss: 0.4368 | valid_loss: 0.4116 | best: 0.3833 | patience: 8/150
Epoch 115/2500 | train_loss: 0.4551 | valid_loss: 0.3822 | best: 0.3822 | patience: 0/150
Epoch 119/2500 | train_loss: 0.4461 | valid_loss: 0.3781 | best: 0.3781 | patience: 0/150
Epoch 120/2500 | train_loss: 0.4326 | valid_loss: 0.3942 | best: 0.3781 | patience: 1/150
Epoch 121/2500 | train_loss: 0.4516 | valid_loss: 0.3771 | best: 0.3771 | patience: 0/150
Epoch 124/2500 | train_loss: 0.4334 | valid_loss: 0.3721 | best: 0.3721 | patience: 0/150
Epoch 130/2500 | train_loss: 0.4405 | valid_loss: 0.3762 | best: 0.3721 | patience: 6/150
Epoch 137/2500 | train_loss: 0.4206 | valid_loss: 0.3710 | best: 0.3710 | patience: 0/150
Epoch 139/2500 | train_loss: 0.4418 | valid_loss: 0.3692 | best: 0.3692 | patience: 0/150
Epoch 140/2500 | train_loss: 0.4335 | valid_loss: 0.3739 | best: 0.3692 | patience: 1/150
Epoch 150/2500 | train_loss: 0.4341 | valid_loss: 0.3824 | best: 0.3692 | patience: 11/150
Epoch 151/2500 | train_loss: 0.4404 | valid_loss: 0.3631 | best: 0.3631 | patience: 0/150
Epoch 155/2500 | train_loss: 0.4353 | valid_loss: 0.3621 | best: 0.3621 | patience: 0/150
Epoch 158/2500 | train_loss: 0.4197 | valid_loss: 0.3618 | best: 0.3618 | patience: 0/150
Epoch 159/2500 | train_loss: 0.4383 | valid_loss: 0.3615 | best: 0.3615 | patience: 0/150
Epoch 160/2500 | train_loss: 0.4465 | valid_loss: 0.3677 | best: 0.3615 | patience: 1/150
Epoch 167/2500 | train_loss: 0.4188 | valid_loss: 0.3578 | best: 0.3578 | patience: 0/150
Epoch 170/2500 | train_loss: 0.4188 | valid_loss: 0.3635 | best: 0.3578 | patience: 3/150
Epoch 172/2500 | train_loss: 0.4332 | valid_loss: 0.3565 | best: 0.3565 | patience: 0/150
Epoch 173/2500 | train_loss: 0.4207 | valid_loss: 0.3554 | best: 0.3554 | patience: 0/150
Epoch 177/2500 | train_loss: 0.4242 | valid_loss: 0.3545 | best: 0.3545 | patience: 0/150
Epoch 180/2500 | train_loss: 0.4231 | valid_loss: 0.3668 | best: 0.3545 | patience: 3/150
Epoch 183/2500 | train_loss: 0.4196 | valid_loss: 0.3528 | best: 0.3528 | patience: 0/150
Epoch 189/2500 | train_loss: 0.4141 | valid_loss: 0.3510 | best: 0.3510 | patience: 0/150
Epoch 190/2500 | train_loss: 0.4218 | valid_loss: 0.4189 | best: 0.3510 | patience: 1/150
Epoch 197/2500 | train_loss: 0.4047 | valid_loss: 0.3488 | best: 0.3488 | patience: 0/150
Epoch 198/2500 | train_loss: 0.4068 | valid_loss: 0.3433 | best: 0.3433 | patience: 0/150
Epoch 200/2500 | train_loss: 0.4208 | valid_loss: 0.3657 | best: 0.3433 | patience: 2/150
Epoch 207/2500 | train_loss: 0.3880 | valid_loss: 0.3433 | best: 0.3433 | patience: 0/150
Epoch 209/2500 | train_loss: 0.3902 | valid_loss: 0.3413 | best: 0.3413 | patience: 0/150
Epoch 210/2500 | train_loss: 0.4282 | valid_loss: 0.3506 | best: 0.3413 | patience: 1/150
Epoch 218/2500 | train_loss: 0.4154 | valid_loss: 0.3379 | best: 0.3379 | patience: 0/150
Epoch 220/2500 | train_loss: 0.4030 | valid_loss: 0.3527 | best: 0.3379 | patience: 2/150
Epoch 224/2500 | train_loss: 0.3876 | valid_loss: 0.3349 | best: 0.3349 | patience: 0/150
Epoch 230/2500 | train_loss: 0.3968 | valid_loss: 0.3358 | best: 0.3349 | patience: 6/150
Epoch 238/2500 | train_loss: 0.3850 | valid_loss: 0.3342 | best: 0.3342 | patience: 0/150
Epoch 240/2500 | train_loss: 0.3913 | valid_loss: 0.3420 | best: 0.3342 | patience: 2/150
Epoch 241/2500 | train_loss: 0.3813 | valid_loss: 0.3303 | best: 0.3303 | patience: 0/150
Epoch 250/2500 | train_loss: 0.3856 | valid_loss: 0.3345 | best: 0.3303 | patience: 9/150
Epoch 260/2500 | train_loss: 0.3818 | valid_loss: 0.3309 | best: 0.3303 | patience: 19/150
Epoch 264/2500 | train_loss: 0.3905 | valid_loss: 0.3278 | best: 0.3278 | patience: 0/150
Epoch 268/2500 | train_loss: 0.3646 | valid_loss: 0.3266 | best: 0.3266 | patience: 0/150
Epoch 270/2500 | train_loss: 0.3822 | valid_loss: 0.3552 | best: 0.3266 | patience: 2/150
Epoch 280/2500 | train_loss: 0.3909 | valid_loss: 0.3296 | best: 0.3266 | patience: 12/150
Epoch 282/2500 | train_loss: 0.3718 | valid_loss: 0.3258 | best: 0.3258 | patience: 0/150
Epoch 288/2500 | train_loss: 0.3663 | valid_loss: 0.3243 | best: 0.3243 | patience: 0/150
Epoch 290/2500 | train_loss: 0.3800 | valid_loss: 0.3294 | best: 0.3243 | patience: 2/150
Epoch 296/2500 | train_loss: 0.3691 | valid_loss: 0.3236 | best: 0.3236 | patience: 0/150
Epoch 297/2500 | train_loss: 0.3840 | valid_loss: 0.3235 | best: 0.3235 | patience: 0/150
Epoch 300/2500 | train_loss: 0.3699 | valid_loss: 0.3253 | best: 0.3235 | patience: 3/150
Epoch 301/2500 | train_loss: 0.3702 | valid_loss: 0.3234 | best: 0.3234 | patience: 0/150
Epoch 310/2500 | train_loss: 0.3549 | valid_loss: 0.3581 | best: 0.3234 | patience: 9/150
Epoch 311/2500 | train_loss: 0.3571 | valid_loss: 0.3219 | best: 0.3219 | patience: 0/150
Epoch 320/2500 | train_loss: 0.3881 | valid_loss: 0.3433 | best: 0.3219 | patience: 9/150
Epoch 327/2500 | train_loss: 0.3457 | valid_loss: 0.3173 | best: 0.3173 | patience: 0/150
Epoch 330/2500 | train_loss: 0.3712 | valid_loss: 0.3196 | best: 0.3173 | patience: 3/150
Epoch 340/2500 | train_loss: 0.3510 | valid_loss: 0.3235 | best: 0.3173 | patience: 13/150
Epoch 350/2500 | train_loss: 0.3372 | valid_loss: 0.3426 | best: 0.3173 | patience: 23/150
Epoch 356/2500 | train_loss: 0.3581 | valid_loss: 0.3170 | best: 0.3170 | patience: 0/150
Epoch 357/2500 | train_loss: 0.3380 | valid_loss: 0.3150 | best: 0.3150 | patience: 0/150
Epoch 360/2500 | train_loss: 0.3787 | valid_loss: 0.3304 | best: 0.3150 | patience: 3/150
Epoch 370/2500 | train_loss: 0.3508 | valid_loss: 0.3453 | best: 0.3150 | patience: 13/150
Epoch 380/2500 | train_loss: 0.3357 | valid_loss: 0.3165 | best: 0.3150 | patience: 23/150
Epoch 381/2500 | train_loss: 0.3501 | valid_loss: 0.3135 | best: 0.3135 | patience: 0/150
Epoch 388/2500 | train_loss: 0.3352 | valid_loss: 0.3125 | best: 0.3125 | patience: 0/150
Epoch 390/2500 | train_loss: 0.3497 | valid_loss: 0.3196 | best: 0.3125 | patience: 2/150
Epoch 392/2500 | train_loss: 0.3324 | valid_loss: 0.3123 | best: 0.3123 | patience: 0/150
Epoch 400/2500 | train_loss: 0.3363 | valid_loss: 0.3195 | best: 0.3123 | patience: 8/150
Epoch 410/2500 | train_loss: 0.3223 | valid_loss: 0.3187 | best: 0.3123 | patience: 18/150
Epoch 420/2500 | train_loss: 0.3160 | valid_loss: 0.3172 | best: 0.3123 | patience: 28/150
Epoch 430/2500 | train_loss: 0.3155 | valid_loss: 0.3222 | best: 0.3123 | patience: 38/150
Epoch 440/2500 | train_loss: 0.3379 | valid_loss: 0.3257 | best: 0.3123 | patience: 48/150
Epoch 450/2500 | train_loss: 0.3247 | valid_loss: 0.3216 | best: 0.3123 | patience: 58/150
Epoch 460/2500 | train_loss: 0.3151 | valid_loss: 0.3619 | best: 0.3123 | patience: 68/150
Epoch 470/2500 | train_loss: 0.2982 | valid_loss: 0.3303 | best: 0.3123 | patience: 78/150
Epoch 480/2500 | train_loss: 0.3030 | valid_loss: 0.3300 | best: 0.3123 | patience: 88/150
Epoch 490/2500 | train_loss: 0.3034 | valid_loss: 0.3379 | best: 0.3123 | patience: 98/150
Epoch 500/2500 | train_loss: 0.3199 | valid_loss: 0.3289 | best: 0.3123 | patience: 108/150
Epoch 510/2500 | train_loss: 0.3000 | valid_loss: 0.3282 | best: 0.3123 | patience: 118/150
Epoch 520/2500 | train_loss: 0.2935 | valid_loss: 0.3343 | best: 0.3123 | patience: 128/150
Epoch 530/2500 | train_loss: 0.2963 | valid_loss: 0.3357 | best: 0.3123 | patience: 138/150
Epoch 540/2500 | train_loss: 0.2787 | valid_loss: 0.3766 | best: 0.3123 | patience: 148/150
Early stopping at epoch 542. Best valid_loss: 0.3123

Fold 1
train: 762 valid: 191
Epoch 001/2500 | train_loss: 0.7012 | valid_loss: 0.6995 | best: 0.6995 | patience: 0/150
Epoch 002/2500 | train_loss: 0.6957 | valid_loss: 0.6857 | best: 0.6857 | patience: 0/150
Epoch 003/2500 | train_loss: 0.6907 | valid_loss: 0.6831 | best: 0.6831 | patience: 0/150
Epoch 007/2500 | train_loss: 0.6828 | valid_loss: 0.6823 | best: 0.6823 | patience: 0/150
Epoch 010/2500 | train_loss: 0.6865 | valid_loss: 0.6867 | best: 0.6823 | patience: 3/150
Epoch 011/2500 | train_loss: 0.6838 | valid_loss: 0.6815 | best: 0.6815 | patience: 0/150
Epoch 013/2500 | train_loss: 0.6866 | valid_loss: 0.6813 | best: 0.6813 | patience: 0/150
Epoch 016/2500 | train_loss: 0.6808 | valid_loss: 0.6796 | best: 0.6796 | patience: 0/150
Epoch 018/2500 | train_loss: 0.6788 | valid_loss: 0.6788 | best: 0.6788 | patience: 0/150
Epoch 020/2500 | train_loss: 0.6813 | valid_loss: 0.6796 | best: 0.6788 | patience: 2/150
Epoch 021/2500 | train_loss: 0.6821 | valid_loss: 0.6774 | best: 0.6774 | patience: 0/150
Epoch 023/2500 | train_loss: 0.6806 | valid_loss: 0.6749 | best: 0.6749 | patience: 0/150
Epoch 024/2500 | train_loss: 0.6769 | valid_loss: 0.6725 | best: 0.6725 | patience: 0/150
Epoch 025/2500 | train_loss: 0.6774 | valid_loss: 0.6707 | best: 0.6707 | patience: 0/150
Epoch 027/2500 | train_loss: 0.6719 | valid_loss: 0.6681 | best: 0.6681 | patience: 0/150
Epoch 028/2500 | train_loss: 0.6748 | valid_loss: 0.6626 | best: 0.6626 | patience: 0/150
Epoch 029/2500 | train_loss: 0.6757 | valid_loss: 0.6626 | best: 0.6626 | patience: 0/150
Epoch 030/2500 | train_loss: 0.6696 | valid_loss: 0.6587 | best: 0.6587 | patience: 0/150
Epoch 031/2500 | train_loss: 0.6688 | valid_loss: 0.6572 | best: 0.6572 | patience: 0/150
Epoch 032/2500 | train_loss: 0.6669 | valid_loss: 0.6522 | best: 0.6522 | patience: 0/150
Epoch 033/2500 | train_loss: 0.6690 | valid_loss: 0.6490 | best: 0.6490 | patience: 0/150
Epoch 034/2500 | train_loss: 0.6594 | valid_loss: 0.6432 | best: 0.6432 | patience: 0/150
Epoch 035/2500 | train_loss: 0.6531 | valid_loss: 0.6356 | best: 0.6356 | patience: 0/150
Epoch 036/2500 | train_loss: 0.6497 | valid_loss: 0.6265 | best: 0.6265 | patience: 0/150
Epoch 037/2500 | train_loss: 0.6421 | valid_loss: 0.6196 | best: 0.6196 | patience: 0/150
Epoch 038/2500 | train_loss: 0.6352 | valid_loss: 0.6098 | best: 0.6098 | patience: 0/150
Epoch 040/2500 | train_loss: 0.6275 | valid_loss: 0.5954 | best: 0.5954 | patience: 0/150
Epoch 042/2500 | train_loss: 0.6285 | valid_loss: 0.5880 | best: 0.5880 | patience: 0/150
Epoch 043/2500 | train_loss: 0.6130 | valid_loss: 0.5858 | best: 0.5858 | patience: 0/150
Epoch 044/2500 | train_loss: 0.6088 | valid_loss: 0.5796 | best: 0.5796 | patience: 0/150
Epoch 047/2500 | train_loss: 0.6223 | valid_loss: 0.5785 | best: 0.5785 | patience: 0/150
Epoch 049/2500 | train_loss: 0.5950 | valid_loss: 0.5706 | best: 0.5706 | patience: 0/150
Epoch 050/2500 | train_loss: 0.6063 | valid_loss: 0.5703 | best: 0.5703 | patience: 0/150
Epoch 052/2500 | train_loss: 0.5920 | valid_loss: 0.5662 | best: 0.5662 | patience: 0/150
Epoch 056/2500 | train_loss: 0.5893 | valid_loss: 0.5611 | best: 0.5611 | patience: 0/150
Epoch 060/2500 | train_loss: 0.5820 | valid_loss: 0.5620 | best: 0.5611 | patience: 4/150
Epoch 063/2500 | train_loss: 0.5832 | valid_loss: 0.5565 | best: 0.5565 | patience: 0/150
Epoch 066/2500 | train_loss: 0.5871 | valid_loss: 0.5531 | best: 0.5531 | patience: 0/150
Epoch 069/2500 | train_loss: 0.5807 | valid_loss: 0.5516 | best: 0.5516 | patience: 0/150
Epoch 070/2500 | train_loss: 0.5706 | valid_loss: 0.5631 | best: 0.5516 | patience: 1/150
Epoch 071/2500 | train_loss: 0.5857 | valid_loss: 0.5496 | best: 0.5496 | patience: 0/150
Epoch 075/2500 | train_loss: 0.5692 | valid_loss: 0.5475 | best: 0.5475 | patience: 0/150
Epoch 078/2500 | train_loss: 0.5708 | valid_loss: 0.5464 | best: 0.5464 | patience: 0/150
Epoch 079/2500 | train_loss: 0.5599 | valid_loss: 0.5456 | best: 0.5456 | patience: 0/150
Epoch 080/2500 | train_loss: 0.5881 | valid_loss: 0.5511 | best: 0.5456 | patience: 1/150
Epoch 084/2500 | train_loss: 0.5821 | valid_loss: 0.5429 | best: 0.5429 | patience: 0/150
Epoch 086/2500 | train_loss: 0.5719 | valid_loss: 0.5412 | best: 0.5412 | patience: 0/150
Epoch 089/2500 | train_loss: 0.5620 | valid_loss: 0.5396 | best: 0.5396 | patience: 0/150
Epoch 090/2500 | train_loss: 0.5740 | valid_loss: 0.5396 | best: 0.5396 | patience: 1/150
Epoch 091/2500 | train_loss: 0.5711 | valid_loss: 0.5386 | best: 0.5386 | patience: 0/150
Epoch 096/2500 | train_loss: 0.5567 | valid_loss: 0.5350 | best: 0.5350 | patience: 0/150
Epoch 097/2500 | train_loss: 0.5587 | valid_loss: 0.5333 | best: 0.5333 | patience: 0/150
Epoch 100/2500 | train_loss: 0.5613 | valid_loss: 0.5808 | best: 0.5333 | patience: 3/150
Epoch 101/2500 | train_loss: 0.5696 | valid_loss: 0.5309 | best: 0.5309 | patience: 0/150
Epoch 106/2500 | train_loss: 0.5514 | valid_loss: 0.5305 | best: 0.5305 | patience: 0/150
Epoch 108/2500 | train_loss: 0.5541 | valid_loss: 0.5282 | best: 0.5282 | patience: 0/150
Epoch 110/2500 | train_loss: 0.5535 | valid_loss: 0.5597 | best: 0.5282 | patience: 2/150
Epoch 113/2500 | train_loss: 0.5540 | valid_loss: 0.5260 | best: 0.5260 | patience: 0/150
Epoch 117/2500 | train_loss: 0.5671 | valid_loss: 0.5225 | best: 0.5225 | patience: 0/150
Epoch 118/2500 | train_loss: 0.5469 | valid_loss: 0.5182 | best: 0.5182 | patience: 0/150
Epoch 120/2500 | train_loss: 0.5605 | valid_loss: 0.5378 | best: 0.5182 | patience: 2/150
Epoch 122/2500 | train_loss: 0.5685 | valid_loss: 0.5161 | best: 0.5161 | patience: 0/150
Epoch 126/2500 | train_loss: 0.5461 | valid_loss: 0.5122 | best: 0.5122 | patience: 0/150
Epoch 128/2500 | train_loss: 0.5529 | valid_loss: 0.5062 | best: 0.5062 | patience: 0/150
Epoch 130/2500 | train_loss: 0.5442 | valid_loss: 0.5061 | best: 0.5061 | patience: 0/150
Epoch 132/2500 | train_loss: 0.5509 | valid_loss: 0.5039 | best: 0.5039 | patience: 0/150
Epoch 135/2500 | train_loss: 0.5406 | valid_loss: 0.5023 | best: 0.5023 | patience: 0/150
Epoch 138/2500 | train_loss: 0.5446 | valid_loss: 0.4955 | best: 0.4955 | patience: 0/150
Epoch 140/2500 | train_loss: 0.5275 | valid_loss: 0.4967 | best: 0.4955 | patience: 2/150
Epoch 141/2500 | train_loss: 0.5128 | valid_loss: 0.4875 | best: 0.4875 | patience: 0/150
Epoch 143/2500 | train_loss: 0.5176 | valid_loss: 0.4820 | best: 0.4820 | patience: 0/150
Epoch 145/2500 | train_loss: 0.5166 | valid_loss: 0.4785 | best: 0.4785 | patience: 0/150
Epoch 147/2500 | train_loss: 0.5161 | valid_loss: 0.4751 | best: 0.4751 | patience: 0/150
Epoch 150/2500 | train_loss: 0.5030 | valid_loss: 0.5159 | best: 0.4751 | patience: 3/150
Epoch 151/2500 | train_loss: 0.5095 | valid_loss: 0.4672 | best: 0.4672 | patience: 0/150
Epoch 154/2500 | train_loss: 0.4894 | valid_loss: 0.4637 | best: 0.4637 | patience: 0/150
Epoch 155/2500 | train_loss: 0.4845 | valid_loss: 0.4601 | best: 0.4601 | patience: 0/150
Epoch 156/2500 | train_loss: 0.4942 | valid_loss: 0.4559 | best: 0.4559 | patience: 0/150
Epoch 158/2500 | train_loss: 0.4952 | valid_loss: 0.4493 | best: 0.4493 | patience: 0/150

In [19]:
results_df = pd.DataFrame(results_large_cnn)

summary_df = results_df.groupby("model").agg(
    log_loss_mean=("log_loss", "mean"),
    log_loss_std=("log_loss", "std"),
    auroc_mean=("auroc", "mean"),
    auroc_std=("auroc", "std"),
)

display(results_df)
display(summary_df)

results_df.to_csv(
    "results/profile_large_cnn_oof_results.csv",
    index=False,
)

,model,fold,log_loss,auroc,params,model_path
0,large_cnn,0,0.313108,0.939646,"{'epochs': 2500, 'batch_size': 8, 'lr': 0.0001...",models/large_cnn_fold_0.pth
1,large_cnn,1,0.311165,0.935659,"{'epochs': 2500, 'batch_size': 8, 'lr': 0.0001...",models/large_cnn_fold_1.pth
2,large_cnn,2,0.263313,0.952270,"{'epochs': 2500, 'batch_size': 8, 'lr': 0.0001...",models/large_cnn_fold_2.pth
3,large_cnn,3,0.421051,0.897697,"{'epochs': 2500, 'batch_size': 8, 'lr': 0.0001...",models/large_cnn_fold_3.pth
4,large_cnn,4,0.267280,0.956507,"{'epochs': 2500, 'batch_size': 8, 'lr': 0.0001...",models/large_cnn_fold_4.pth

           log_loss_mean  log_loss_std  auroc_mean  auroc_std
model
large_cnn       0.315183      0.063667    0.936356   0.023266

In [11]:
train_main_uids = oof_split_df.loc[oof_split_df["split"] == "train_main", "uid"].values
valid_meta_uids = oof_split_df.loc[oof_split_df["split"] == "valid_meta", "uid"].values
test_final_uids = oof_split_df.loc[oof_split_df["split"] == "test_final", "uid"].values

uid_to_idx = {uid: idx for idx, uid in enumerate(uids_processed_volumes)}

valid_meta_idx = np.array([uid_to_idx[uid] for uid in valid_meta_uids])
test_final_idx = np.array([uid_to_idx[uid] for uid in test_final_uids])

In [9]:
import torch

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")


def load_small_cnn(fold):
    model = Simple3DCNN()
    path = f"models/small_cnn_fold_{fold}.pth"

    model.load_state_dict(
        torch.load(path, map_location=device)
    )

    model = model.to(device)
    model.eval()

    return model


def load_large_cnn(fold):
    model = Simple3DCNNLarge()
    path = f"models/large_cnn_fold_{fold}.pth"

    model.load_state_dict(
        torch.load(path, map_location=device)
    )

    model = model.to(device)
    model.eval()

    return model
def load_profile_mlp(fold, input_size):
    model = ProfileMLP(input_size=input_size)
    path = f"models/profile_mlp_fold_{fold}.pth"

    model.load_state_dict(
        torch.load(path, map_location=device)
    )

    model = model.to(device)
    model.eval()

    return model
def load_profile_logreg(fold):
    path = f"models/profile_logreg_fold_{fold}.joblib"
    model = joblib.load(path)

    return model

In [12]:
valid_preds = {
    "profile_logreg": [],
    "profile_mlp": [],
    "small_cnn": [],
    "large_cnn": [],
}

test_preds = {
    "profile_logreg": [],
    "profile_mlp": [],
    "small_cnn": [],
    "large_cnn": [],
}

for fold in range(5):
    print(f"Fold {fold}")

    profile_logreg_model = load_profile_logreg(fold)
    profile_mlp_model = load_profile_mlp(
        fold,
        input_size=X_profiles.shape[1],
    )
    small_cnn_model = load_small_cnn(fold)
    large_cnn_model = load_large_cnn(fold)

    valid_preds["profile_logreg"].append(
        profile_logreg_model.predict_proba(X_profiles[valid_meta_idx])[:, 1]
    )

    test_preds["profile_logreg"].append(
        profile_logreg_model.predict_proba(X_profiles[test_final_idx])[:, 1]
    )

    valid_preds["profile_mlp"].append(
        predict_profile_mlp(profile_mlp_model, X_profiles[valid_meta_idx])
    )

    test_preds["profile_mlp"].append(
        predict_profile_mlp(profile_mlp_model, X_profiles[test_final_idx])
    )

    valid_preds["small_cnn"].append(
        predict_cnn_model(small_cnn_model, X_volumes[valid_meta_idx])
    )

    test_preds["small_cnn"].append(
        predict_cnn_model(small_cnn_model, X_volumes[test_final_idx])
    )

    valid_preds["large_cnn"].append(
        predict_cnn_model(large_cnn_model, X_volumes[valid_meta_idx])
    )

    test_preds["large_cnn"].append(
        predict_cnn_model(large_cnn_model, X_volumes[test_final_idx])
    )

Fold 0

C:\Users\abram\AppData\Local\Temp\ipykernel_43452\2958847578.py:37: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  torch.load(path, map_location=device)
C:\Users\abram\AppData\Local\Temp\ipykernel_43452\2958847578.py:11: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  torch.load(path, map_location=device)
C:\Users\abram\AppData\Local\Temp\ipykernel_43452\2958847578.py:25: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  torch.load(path, map_location=device)

Fold 1

C:\Users\abram\AppData\Local\Temp\ipykernel_43452\2958847578.py:37: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  torch.load(path, map_location=device)
C:\Users\abram\AppData\Local\Temp\ipykernel_43452\2958847578.py:11: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  torch.load(path, map_location=device)
C:\Users\abram\AppData\Local\Temp\ipykernel_43452\2958847578.py:25: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  torch.load(path, map_location=device)

Fold 2

C:\Users\abram\AppData\Local\Temp\ipykernel_43452\2958847578.py:37: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  torch.load(path, map_location=device)
C:\Users\abram\AppData\Local\Temp\ipykernel_43452\2958847578.py:11: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  torch.load(path, map_location=device)
C:\Users\abram\AppData\Local\Temp\ipykernel_43452\2958847578.py:25: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  torch.load(path, map_location=device)

Fold 3

C:\Users\abram\AppData\Local\Temp\ipykernel_43452\2958847578.py:37: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  torch.load(path, map_location=device)
C:\Users\abram\AppData\Local\Temp\ipykernel_43452\2958847578.py:11: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  torch.load(path, map_location=device)
C:\Users\abram\AppData\Local\Temp\ipykernel_43452\2958847578.py:25: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  torch.load(path, map_location=device)

Fold 4

C:\Users\abram\AppData\Local\Temp\ipykernel_43452\2958847578.py:37: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  torch.load(path, map_location=device)
C:\Users\abram\AppData\Local\Temp\ipykernel_43452\2958847578.py:11: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  torch.load(path, map_location=device)
C:\Users\abram\AppData\Local\Temp\ipykernel_43452\2958847578.py:25: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  torch.load(path, map_location=device)

In [15]:
X_meta_valid_mean = np.column_stack([
    np.mean(valid_preds["profile_logreg"], axis=0),
    np.mean(valid_preds["profile_mlp"], axis=0),
    np.mean(valid_preds["small_cnn"], axis=0),
    np.mean(valid_preds["large_cnn"], axis=0),
])

X_meta_test_mean = np.column_stack([
    np.mean(test_preds["profile_logreg"], axis=0),
    np.mean(test_preds["profile_mlp"], axis=0),
    np.mean(test_preds["small_cnn"], axis=0),
    np.mean(test_preds["large_cnn"], axis=0),
])

In [16]:
X_meta_valid_all = np.column_stack([
    *valid_preds["profile_logreg"],
    *valid_preds["profile_mlp"],
    *valid_preds["small_cnn"],
    *valid_preds["large_cnn"],
])

X_meta_test_all = np.column_stack([
    *test_preds["profile_logreg"],
    *test_preds["profile_mlp"],
    *test_preds["small_cnn"],
    *test_preds["large_cnn"],
])

In [17]:
print(X_meta_valid_mean.shape)
print(X_meta_test_mean.shape)

print(X_meta_valid_all.shape)
print(X_meta_test_all.shape)

(272, 4)
(137, 4)
(272, 20)
(137, 20)

In [18]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import log_loss, roc_auc_score
import pandas as pd

y_meta_valid = y_volumes[valid_meta_idx]
y_meta_test = y_volumes[test_final_idx]

meta_results = []

for name, Xv, Xt in [
    ("mean_folds", X_meta_valid_mean, X_meta_test_mean),
    ("all_folds", X_meta_valid_all, X_meta_test_all),
]:
    meta_model = LogisticRegression(
        C=0.1,
        max_iter=1000,
        solver="lbfgs",
    )

    meta_model.fit(Xv, y_meta_valid)

    valid_proba = meta_model.predict_proba(Xv)[:, 1]
    test_proba = meta_model.predict_proba(Xt)[:, 1]

    meta_results.append({
        "model": name,
        "valid_log_loss": log_loss(y_meta_valid, valid_proba),
        "valid_auroc": roc_auc_score(y_meta_valid, valid_proba),
        "test_log_loss": log_loss(y_meta_test, test_proba),
        "test_auroc": roc_auc_score(y_meta_test, test_proba),
    })

meta_results_df = pd.DataFrame(meta_results)
meta_results_df

        model  valid_log_loss  valid_auroc  test_log_loss  test_auroc
0  mean_folds        0.402446     0.923665       0.374677    0.938925
1   all_folds        0.347939     0.932940       0.316990    0.940860

In [19]:
blend_valid = X_meta_valid_mean.mean(axis=1)
blend_test = X_meta_test_mean.mean(axis=1)

blend_results = {
    "model": "simple_blend_mean_4_models",
    "valid_log_loss": log_loss(y_meta_valid, blend_valid),
    "valid_auroc": roc_auc_score(y_meta_valid, blend_valid),
    "test_log_loss": log_loss(y_meta_test, blend_test),
    "test_auroc": roc_auc_score(y_meta_test, blend_test),
}

pd.concat([
    meta_results_df,
    pd.DataFrame([blend_results]),
], ignore_index=True)

,model,valid_log_loss,valid_auroc,test_log_loss,test_auroc
0,mean_folds,0.402446,0.923665,0.374677,0.938925
1,all_folds,0.347939,0.932940,0.316990,0.940860
2,simple_blend_mean_4_models,0.374393,0.912315,0.340804,0.931613

In [20]:
joblib.dump(
    meta_model,
    "models/meta_logreg_all_folds.joblib",
)

['models/meta_logreg_all_folds.joblib']

In [21]:
final_predictions_df = pd.DataFrame({
    "uid": test_final_uids,
    "y_true": y_meta_test,
    "probability": test_proba,
})

final_predictions_df.to_csv(
    "meta_test_predictions.csv",
    index=False,
)

## Podsumowanie procesu OOF i stackingu

W eksperymencie zastosowano podział danych na trzy niezależne części: `train_main`, `valid_meta` oraz `test_final`. Zbiór `train_main` został dodatkowo podzielony na pięć foldów za pomocą `StratifiedKFold`, dzięki czemu zachowano zbliżone proporcje klas w każdym foldzie.

Dla każdego folda wytrenowano cztery modele bazowe:

- regresję logistyczną wykorzystującą profile obrazów,
- sieć MLP wykorzystującą profile obrazów,
- mniejszy model 3D CNN wykorzystujący pełne wolumeny,
- większy model 3D CNN wykorzystujący pełne wolumeny.

Łącznie powstało 20 modeli bazowych: cztery rodzaje modeli wytrenowane osobno dla pięciu foldów. Po zakończeniu ich treningu modele nie były już ponownie dopasowywane.

Sprawdzono trzy sposoby połączenia modeli:

1. `mean_folds` – uśrednienie predykcji pięciu foldów osobno dla każdego rodzaju modelu, a następnie przekazanie czterech cech do meta-modelu;
2. `all_folds` – przekazanie do meta-modelu wszystkich 20 predykcji bez wcześniejszego uśredniania;
3. `simple_blend_mean_4_models` – proste uśrednienie predykcji czterech modeli bez trenowania meta-modelu.

Rolę meta-modelu pełniła regresja logistyczna trenowana na zbiorze `valid_meta`. Ostateczna ocena została przeprowadzona na niezależnym zbiorze `test_final`, który nie uczestniczył ani w treningu modeli bazowych, ani w treningu meta-modelu.

Najlepszy wynik uzyskał wariant `all_folds`:

- **test log loss: 0.3170**
- **test AUROC: 0.9409**

Zastosowany proces ogranicza ryzyko data leakage poprzez rozdzielenie danych używanych do treningu modeli bazowych, treningu meta-modelu oraz końcowego testu. Technicznie meta-model został wytrenowany na osobnym zbiorze `valid_meta`, a nie na klasycznych predykcjach OOF ze zbioru `train_main`. Jest to więc połączenie treningu foldowego modeli bazowych, ensemble oraz stackingu z wydzielonym zbiorem dla meta-modelu.